In [5]:
import datetime

def calculate_age(bd):
    try:
        bd = datetime.datetime.strptime(bd, "%Y-%m-%d")
        current = datetime.datetime.now()
        if(current.month < bd.month and current.day < bd.day):
            age = current.year - bd.year
        else:
            age = current.year - bd.year - 1
        age = current.year - bd.year - ((current.month, current.day) < (bd.month, bd.day))
        return age
    except ValueError:
        return "Invalid date format. Please use the format 'YYYY-MM-DD'"
    except Exception as e:
        return f"An error occurred: {str(e)}"

bd = input("Enter your birthdate (YYYY-MM-DD): ")
age = calculate_age(bd)
print(f"Your current age is: {age} years")


Your current age is: 20 years


In [13]:
import datetime

def working_days(d1, d2):
    day1 = datetime.datetime.strptime(d1, "%Y-%m-%d")
    day2 = datetime.datetime.strptime(d2, "%Y-%m-%d")
    
    count = 0
    while day1 <= day2:
        if day1.weekday() < 5:
            count += 1
        day1 += datetime.timedelta(days=1)
    
    return count

d1 = input("Enter first date (YYYY-MM-DD): ")
d2 = input("Enter second date (YYYY-MM-DD): ")
c = working_days(d1,d2)

print(f"Weekdays count: {c}")


0
0
0
1
2
3
4
5
Weekdays count: 5


In [21]:
import math

x1 = float(input('Enter x1'))
y1 = float(input('Enter y1'))
x2 = float(input('Enter x2'))
y2 = float(input('Enter y2'))

print(math.sqrt((x2 - x1)**2 + (y2 - y1)**2))

55.47071299343465


In [ ]:
import numpy as np

A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

element_wise_sum = A + B
element_wise_product = A * B

print("\nElement-wise sum of A and B:")
print(element_wise_sum)
print("\nElement-wise product of A and B:")
print(element_wise_product)

dot_product = np.dot(A, B)
print("\nDot product of A and B:")
print(dot_product)

determinant_A = np.linalg.det(A)
print("\nDeterminant of matrix A:", determinant_A)

try:
    inverse_B = np.linalg.inv(B)
    print("\nInverse of matrix B:")
    print(inverse_B)
except np.linalg.LinAlgError:
    print("\nMatrix B is not invertible.")

In [29]:
import pandas as pd

data = [
    ['Alice', 25, 'New York'],
    ['Bob', 30, 'Los Angeles'],
    ['Charlie', 22, 'Chiacago'],
    ['David', 35, 'San Francisco']
]

columns = ['Name', 'Age', 'City']

df = pd.DataFrame(data, columns=columns)
print(df)
print('\n\n')
print(df.head(2))
print('\n\n')
print(df[df['Age'] >= 30])
df['Country'] = 'USA'
print('\n\n')
print(df)
df.to_csv('people.csv', index=False)

      Name  Age           City
0    Alice   25       New York
1      Bob   30    Los Angeles
2  Charlie   22       Chiacago
3    David   35  San Francisco



    Name  Age         City
0  Alice   25     New York
1    Bob   30  Los Angeles



    Name  Age           City
1    Bob   30    Los Angeles
3  David   35  San Francisco



      Name  Age           City Country
0    Alice   25       New York     USA
1      Bob   30    Los Angeles     USA
2  Charlie   22       Chiacago     USA
3    David   35  San Francisco     USA


In [33]:
import pandas as pd

data = [
    ['Apple', 10],
    ['Banana', 15],
    ['Orange', 20],
    ['Apple', 12],
    ['Banana', 12],
]

columns = ['Product', 'Quantity']

df = pd.DataFrame(data, columns=columns)
print(df)
print('\n\n')
print(df.groupby('Product')['Quantity'].sum().reset_index())
print('\n\n')
print(df['Quantity'].mean())

  Product  Quantity
0   Apple        10
1  Banana        15
2  Orange        20
3   Apple        12
4  Banana        12



  Product  Quantity
0   Apple        22
1  Banana        27
2  Orange        20
13.8


In [36]:
import numpy as np

a = np.arange(11)
print(a)
o_n = a[a % 2 != 0]
print(o_n)
a[a % 2 != 0] = -1
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1 10]


In [54]:
import numpy as np

array_1d = np.arange(10)

# Reshape the 1D array into a 2D array with 2 rows
array_2d = array_1d.reshape(2, -1)

print(array_2d)
print('\n\n')
print(np.random.randint(0, 11, size=(3, 3)))

[[0 1 2 3 4]
 [5 6 7 8 9]]



[[1 5 2]
 [6 2 1]
 [6 1 7]]


In [67]:
import numpy as np
print(np.identity(3))

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

print(vector1 * vector2)

a = np.array(
    [[2,5,4,8,9,77,5,9,9],
    [2,5,4,8,9,77,5,9,9],
    [2,5,4,8,9,77,5,9,9],
    [2,5,4,8,9,77,5,9,9],
    [2,5,4,8,9,77,5,9,9]]
)

print(a.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 4 10 18]
(5, 9)


In [73]:
import numpy as np 

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

i = np.where(arr == 1)

arr[i] = 6

print(arr)
a = int(input('Enter row no')) - 1
print(arr[a])

[[6 2 3 4]
 [5 6 7 8]]
[6 2 3 4]


In [75]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Reshape the array as per the expected output
output = a.reshape(1, -1, 1)

print(output)

[[[1]
  [2]
  [3]
  [4]
  [5]
  [6]
  [7]
  [8]]]


In [78]:
import datetime

current = datetime.datetime.now()
current_date = current.strftime("%Y-%m-%d")
current_time = current.strftime("%H:%M:%S")
print(current_date)
print(current_time)

2023-09-12
14:41:11
