In [6]:
import numpy as np

r = np.random.rand(4, 4)
r = (r * 100).astype(int)
d = r.diagonal()

print(r)
print(d)

Diagonal elements:
[[99 54 33 19]
 [82 88 31  9]
 [17 60 66 36]
 [14 46 98 15]]
[99 88 66 15]


In [10]:
r = np.random.rand(3,4)
r = (r*100).astype(int)

def get_sum(r):
    cs = np.sum(r, axis=0)
    rs = np.sum(r, axis=1)
    return cs, rs

print(get_sum(r))

(array([126, 188, 179, 132]), array([238, 249, 138]))


In [13]:
import numpy as np

def reshape_array(arr, ta):
    try:
        a = arr.reshape(ta)
        return a
    except ValueError:
        raise ValueError(f"Cannot reshape the input array to shape {ta}")


arr = np.array([int(item) for item in input('Enter 1D array').split()])
ta = tuple(int(item) for item in input('Enter 2d dimensions').split())

try:
    result = reshape_array(arr, ta)
    print("Reshaped array:")
    print(result)
except ValueError as e:
    print(f"Error: {e}")

Error: Cannot reshape the input array to shape (4, 1)


In [17]:
def sum(r):
    return r.sum()

In [22]:
def convert_array_type(input_array, data_type):
    try:
        # Attempt to convert the input array to the specified data type
        converted_array = input_array.astype(data_type)
        return converted_array
    except ValueError:
        raise ValueError("Conversion to the specified data type failed.")
    
arr = np.array(
    [[1+3j,2 + 2j,3 + 1j,4 - 9j],
    [1+3j,2 + 2j,3 + 1j,4 - 9j],
    [1+3j,2 + 2j,3 + 1j,4 - 9j]]
)
convert_array_type(arr, str)

array([['(1+3j)', '(2+2j)', '(3+1j)', '(4-9j)'],
       ['(1+3j)', '(2+2j)', '(3+1j)', '(4-9j)'],
       ['(1+3j)', '(2+2j)', '(3+1j)', '(4-9j)']], dtype='<U64')

In [46]:
def join_arrays(*arr, axis=0):
    try:
        result = np.concatenate(arr, axis=axis)
        return result
    except ValueError:
        raise ValueError("Concatenation of input arrays failed.")
    
a1 = np.array([[1, 2]])
a2 = np.array([[5, 6]])
a3 = np.array([[7, 8]])

join_arrays(a1, a2, a3, axis=0)

try:
    result = join_arrays(a1, a2, a3, axis=1)
    print("Joined array:")
    print(result)
except ValueError as e:
    print(f"Error: {e}")

Joined array:
[[1 2 5 6 7 8]]


In [82]:
import numpy as np

def split_numpy_array(arr, k):
    if k <= 0 or len(arr) % k != 0:
        return None  # Cannot split into k equal-sized subarrays

    subarray_size = len(arr) // k
    subarrays = [arr[i * subarray_size : (i + 1) * subarray_size] for i in range(k)]

    return subarrays

# Example usage:
original_array = np.array([[1, 2, 4, 5], [3, 4, 4, 5], [5, 6, 2, 1], [7, 8, 10, 12]])
k = 4

result = split_numpy_array(original_array, k)
if result is not None:
    print("Split into equal-sized subarrays:")
    for subarray in result:
        print(subarray)
else:
    print("Cannot split into equal-sized subarrays.")


Split into equal-sized subarrays:
[[1 2 4 5]]
[[3 4 4 5]]
[[5 6 2 1]]
[[ 7  8 10 12]]


In [67]:

def sort_by_column(arr, k):
    sorted_indices = np.argsort(arr[:, k])
    sorted_array = arr[sorted_indices]
    return sorted_array

arr = np.random.rand(4,4)
print(arr)
try:
    print(sort_by_column(arr, 2))
except IndexError as e:
    print("Error")

[[0.98361261 0.76118837 0.27907648 0.07580825]
 [0.4466552  0.76739249 0.08583247 0.57193585]
 [0.86943717 0.62223408 0.11125443 0.25284174]
 [0.56069939 0.62582662 0.61564369 0.12900942]]
[[0.4466552  0.76739249 0.08583247 0.57193585]
 [0.86943717 0.62223408 0.11125443 0.25284174]
 [0.98361261 0.76118837 0.27907648 0.07580825]
 [0.56069939 0.62582662 0.61564369 0.12900942]]


In [1]:
import keyboard, time

a = '''
a = {
    "length" : [4,5,6,7,8],
    "width" : [2,3,2.5,4,3.5]
}

df = pd.DataFrame(a)

def area(df):
    a = []
    for i in range(df.shape[0]):
        area = df.loc[i][0] * df.loc[i][1]
        a.append(area)
    return a

df['Area'] = area(df)
df

'''
time.sleep(2)
keyboard.write(a)